#!/bin/sh


REMDIR="/segfs/bliss/projects/LIMA/build/depot_win/win_vc9/pco"
REMHOST="blissadm@lid00a"
#LOCDIR="/c/blissadm/git/pco/Lima/install"
LOCDIR="../../install"
TMPDIR="/t/rhoms1"
DLL="Lima/liblimapco.dll"
LOG="./doc/VERSION.log"

DT=`date +"%Y-%m-%d_%H%M%S"`
INSTALL="install-${DT}"
INSTALLBETA="install-beta"

{
echo ${INSTALL} 
echo
./ident.exe ${LOCDIR}/${DLL}
}> ${LOCDIR}/INSTALL_VERSION.txt

mkdir -p ${TMPDIR}/${INSTALL}

cp -r ${LOCDIR}/ ${TMPDIR}/${INSTALL}

cp -r ${LOCDIR}/ ${TMPDIR}/${INSTALLBETA}

scp -r ${TMPDIR}/${INSTALL} ${REMHOST}:${REMDIR}

{
echo
date "+%Y/%m/%d %H:%M:%S =========================================="
echo "scp: copied local directory to segfs and /tmp_14_days:"
echo "from: [${LOCDIR}/]" 
echo "  to: [${REMHOST}:${REMDIR}/${INSTALL}]"
echo "  to: [${TMPDIR}/${INSTALL}]"
echo "  to: [${TMPDIR}/${INSTALLBETA}]"
echo
} > ${LOG}.bck.bck

cat ${LOG}.bck.bck

cat ${LOG} >> ${LOG}.bck.bck

cp -f ${LOG} ${LOG}.bck
mv -f ${LOG}.bck.bck ${LOG}





